### ISSUE TITLE
Issue with importcsv

### ISSUE THREAD

**Issue by robhoney** [UMWRG/csv-app#4]
I have an import file which imports ok with older versions of ImportCSV, but not the latest. The output from ImportCSV:

```
33252 2019-11-27 11:06:35,816 - INFO - No metadata found for node file Nodes-BurstPipeNetwork-Guildford.csv
33252 2019-11-27 11:06:35,817 - INFO - Calling: add_attributes
33252 2019-11-27 11:06:35,818 - INFO - Args {'add_attributes': {}}
33252 2019-11-27 11:06:36,906 - ERROR - {'message': 'Server:Internal Error', 'code': '200'}
Traceback (most recent call last):
  File "importcsv.py", line 488, in read_nodes
    node = self.read_node_line(line, attrs, field_idx, metadata, units)
  File "importcsv.py", line 551, in read_node_line
    node = self.add_data(node, attrs, linedata, metadata, units=units, restrictions=restrictions)
  File "importcsv.py", line 958, in add_data
    added_attributes = self.connection.add_attributes(attrs=attributes)
  File "C:\HydraSrc\csv-app-master\ImportCSV\hydra_client\connection\base_connection.py", line 33, in wrapped
    return self.call(name, *args, **kwargs)
  File "C:\HydraSrc\csv-app-master\ImportCSV\hydra_client\connection\remote_json_connection.py", line 93, in call
    raise RequestError(err)
hydra_client.exception.RequestError: {'message': 'Server:Internal Error', 'code': '200'}
33252 2019-11-27 11:06:36,915 - ERROR - {'message': "An error has occurred in file Nodes-BurstPipeNetwork-Guildford.csv at line 3: {'message': 'Server:Internal Error', 'code': '200'}", 'code': '200'}
Traceback (most recent call last):
  File "importcsv.py", line 488, in read_nodes
    node = self.read_node_line(line, attrs, field_idx, metadata, units)
  File "importcsv.py", line 551, in read_node_line
    node = self.add_data(node, attrs, linedata, metadata, units=units, restrictions=restrictions)
  File "importcsv.py", line 958, in add_data
    added_attributes = self.connection.add_attributes(attrs=attributes)
  File "C:\HydraSrc\csv-app-master\ImportCSV\hydra_client\connection\base_connection.py", line 33, in wrapped
    return self.call(name, *args, **kwargs)
  File "C:\HydraSrc\csv-app-master\ImportCSV\hydra_client\connection\remote_json_connection.py", line 93, in call
    raise RequestError(err)
hydra_client.exception.RequestError: {'message': 'Server:Internal Error', 'code': '200'}
```

The output from the server:
```
19816 2019-11-27 11:06:35,675 - INFO - Call took: 0:00:00.078054
19816 2019-11-27 11:06:35,680 - INFO - Committing...
19816 2019-11-27 11:06:35,681 - INFO - Closing session
19816 2019-11-27 11:06:36,825 - INFO - Received request: <function AttributeService.add_attributes at 0x000002E50340EA60>
19816 2019-11-27 11:06:36,829 - CRITICAL - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\HydraSrc\hydra-server-master\hydra_server\__init__.py", line 194, in call_wrapper
    res =  ctx.service_class.call_wrapper(ctx)
  File "C:\Users\honeywillrs\AppData\Local\Continuum\anaconda3\lib\site-packages\spyne\service.py", line 194, in call_wrapper
    return ctx.function(*args)
  File "C:\HydraSrc\hydra-server-master\hydra_server\server\attributes.py", line 100, in add_attributes
    attrs = attributes.add_attributes(attrs, **ctx.in_header.__dict__)
  File "C:\HydraSrc\hydra-server-master\hydra_base\lib\attributes.py", line 214, in add_attributes
    for potential_new_attr in attrs:
TypeError: 'NoneType' object is not iterable
19816 2019-11-27 11:06:36,868 - CRITICAL - 'TypeError' object has no attribute 'message'
Traceback (most recent call last):
  File "C:\HydraSrc\hydra-server-master\hydra_server\__init__.py", line 194, in call_wrapper
    res =  ctx.service_class.call_wrapper(ctx)
  File "C:\Users\honeywillrs\AppData\Local\Continuum\anaconda3\lib\site-packages\spyne\service.py", line 194, in call_wrapper
    return ctx.function(*args)
  File "C:\HydraSrc\hydra-server-master\hydra_server\server\attributes.py", line 100, in add_attributes
    attrs = attributes.add_attributes(attrs, **ctx.in_header.__dict__)
  File "C:\HydraSrc\hydra-server-master\hydra_base\lib\attributes.py", line 214, in add_attributes
    for potential_new_attr in attrs:
TypeError: 'NoneType' object is not iterable
```

**Comment by knoxsp** [comment]
Can you update hydra-client-python?
You can use pip or pull from master, depending on how you’ve got it set up.
This issue has been caused because the list of attributes is not reaching hydra. I’ve fixed this issue (hopefully!) on the latest hydra-client-python

Steve
